using System.Text;
using System.Threading.Tasks;

namespace Fall2025_Project3_nchubbell.Services
{
    public class FakeAIReviewService : IAIReviewService
    {
        public Task<string> GenerateMovieReviewsAsync(string title, string? description, int reviewCount)
        {
            var sb = new StringBuilder();

            for (int i = 1; i <= reviewCount; i++)
            {
                sb.AppendLine($"Review {i} for {title}:");
                sb.AppendLine("This is a placeholder review generated by the FakeAIReviewService.");
                sb.AppendLine();
            }

            return Task.FromResult(sb.ToString());
        }

        public Task<string> GenerateActorTweetsAsync(string actorName, int tweetCount)
        {
            var sb = new StringBuilder();

            for (int i = 1; i <= tweetCount; i++)
            {
                sb.AppendLine($"Comment {i} about {actorName}:");
                sb.AppendLine("This is a placeholder actor comment generated by the FakeAIReviewService.");
                sb.AppendLine();
            }

            return Task.FromResult(sb.ToString());
        }
    }
}
